export enum ConferenceAttribute{ 
    JOB_STATUS_PENDING = 'PENDING',
    JOB_STATUS_RUNNING = 'RUNNING',
    JOB_STATUS_COMPLETED = 'COMPLETED',
    JOB_STATUS_FAILED = 'FAILED',
    JOB_STATUS_CANCELLED = 'CANCELLED',
}